// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package gateway

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PingResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type InfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{2}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

type InfoResponse struct {
	Databases            []*DatabaseService `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{3}
}

func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (m *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(m, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetDatabases() []*DatabaseService {
	if m != nil {
		return m.Databases
	}
	return nil
}

type DatabaseService struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Services             []*ServiceInfo `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DatabaseService) Reset()         { *m = DatabaseService{} }
func (m *DatabaseService) String() string { return proto.CompactTextString(m) }
func (*DatabaseService) ProtoMessage()    {}
func (*DatabaseService) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{4}
}

func (m *DatabaseService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseService.Unmarshal(m, b)
}
func (m *DatabaseService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseService.Marshal(b, m, deterministic)
}
func (m *DatabaseService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseService.Merge(m, src)
}
func (m *DatabaseService) XXX_Size() int {
	return xxx_messageInfo_DatabaseService.Size(m)
}
func (m *DatabaseService) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseService.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseService proto.InternalMessageInfo

func (m *DatabaseService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DatabaseService) GetServices() []*ServiceInfo {
	if m != nil {
		return m.Services
	}
	return nil
}

type ServiceInfo struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metadata             string        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Methods              []*MethodInfo `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{5}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceInfo) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *ServiceInfo) GetMethods() []*MethodInfo {
	if m != nil {
		return m.Methods
	}
	return nil
}

type MethodInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsClientStream       bool     `protobuf:"varint,2,opt,name=isClientStream,proto3" json:"isClientStream,omitempty"`
	IsServerStream       bool     `protobuf:"varint,3,opt,name=isServerStream,proto3" json:"isServerStream,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodInfo) Reset()         { *m = MethodInfo{} }
func (m *MethodInfo) String() string { return proto.CompactTextString(m) }
func (*MethodInfo) ProtoMessage()    {}
func (*MethodInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{6}
}

func (m *MethodInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodInfo.Unmarshal(m, b)
}
func (m *MethodInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodInfo.Marshal(b, m, deterministic)
}
func (m *MethodInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodInfo.Merge(m, src)
}
func (m *MethodInfo) XXX_Size() int {
	return xxx_messageInfo_MethodInfo.Size(m)
}
func (m *MethodInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MethodInfo proto.InternalMessageInfo

func (m *MethodInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MethodInfo) GetIsClientStream() bool {
	if m != nil {
		return m.IsClientStream
	}
	return false
}

func (m *MethodInfo) GetIsServerStream() bool {
	if m != nil {
		return m.IsServerStream
	}
	return false
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "io.agoradb.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "io.agoradb.PingResponse")
	proto.RegisterType((*InfoRequest)(nil), "io.agoradb.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "io.agoradb.InfoResponse")
	proto.RegisterType((*DatabaseService)(nil), "io.agoradb.DatabaseService")
	proto.RegisterType((*ServiceInfo)(nil), "io.agoradb.ServiceInfo")
	proto.RegisterType((*MethodInfo)(nil), "io.agoradb.MethodInfo")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5) }

var fileDescriptor_f1a937782ebbded5 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x4f, 0xc2, 0x30,
	0x14, 0xc6, 0x19, 0xa0, 0xc0, 0x1b, 0x68, 0xd2, 0x18, 0x6d, 0xf0, 0x42, 0xaa, 0x31, 0x9c, 0x16,
	0x03, 0x27, 0xe3, 0x4d, 0x4d, 0x0c, 0x07, 0x13, 0x33, 0x12, 0x0f, 0xdc, 0x8a, 0x3c, 0xe7, 0x12,
	0xb6, 0xce, 0xb5, 0x60, 0x3c, 0xfb, 0x8f, 0x9b, 0xb5, 0x1d, 0xeb, 0x90, 0xdb, 0xde, 0xfb, 0x7e,
	0xaf, 0xdf, 0x97, 0xbd, 0x07, 0x83, 0x88, 0x2b, 0xfc, 0xe6, 0x3f, 0x41, 0x96, 0x0b, 0x25, 0x08,
	0xc4, 0x22, 0xe0, 0x91, 0xc8, 0xf9, 0x6a, 0xc9, 0xae, 0xc0, 0x7f, 0x8d, 0xd3, 0x28, 0xc4, 0xaf,
	0x0d, 0x4a, 0x45, 0xce, 0xe0, 0x68, 0xcb, 0xd7, 0x1b, 0xa4, 0xde, 0xc8, 0x1b, 0xf7, 0x42, 0x53,
	0xb0, 0x6b, 0xe8, 0x1b, 0x48, 0x66, 0x22, 0x95, 0x58, 0x50, 0x6f, 0x2e, 0xa5, 0x0b, 0x36, 0x00,
	0x7f, 0x96, 0x7e, 0x08, 0xfb, 0x14, 0x9b, 0x41, 0xdf, 0x94, 0x76, 0xe8, 0x0e, 0x7a, 0x2b, 0xae,
	0xf8, 0x92, 0x4b, 0x94, 0xd4, 0x1b, 0xb5, 0xc6, 0xfe, 0xe4, 0x32, 0xa8, 0x92, 0x04, 0x4f, 0x56,
	0x9c, 0x63, 0xbe, 0x8d, 0xdf, 0x31, 0xac, 0x68, 0xb6, 0x80, 0xd3, 0x3d, 0x95, 0x10, 0x68, 0xa7,
	0x3c, 0x29, 0x13, 0xe8, 0x6f, 0x32, 0x85, 0xae, 0x34, 0xb2, 0xa4, 0x4d, 0x6d, 0x70, 0xe1, 0x1a,
	0xd8, 0x51, 0x1d, 0x6a, 0x07, 0x32, 0x01, 0xbe, 0x23, 0x1c, 0x7c, 0x77, 0x08, 0xdd, 0x04, 0x15,
	0x2f, 0xf2, 0xd0, 0xa6, 0xee, 0xef, 0x6a, 0x72, 0x0b, 0x9d, 0x04, 0xd5, 0xa7, 0x58, 0x49, 0xda,
	0xd2, 0x96, 0xe7, 0xae, 0xe5, 0x8b, 0x96, 0xb4, 0x63, 0x89, 0xb1, 0x0c, 0xa0, 0x6a, 0x1f, 0xf4,
	0xbb, 0x81, 0x93, 0x58, 0x3e, 0xae, 0x63, 0x4c, 0xd5, 0x5c, 0xe5, 0xc8, 0x13, 0xed, 0xda, 0x0d,
	0xf7, 0xba, 0x86, 0x2b, 0xc2, 0x63, 0x6e, 0xb9, 0x56, 0xc9, 0xb9, 0xdd, 0xc9, 0xaf, 0x07, 0x9d,
	0x67, 0x73, 0x01, 0xe4, 0x1e, 0xda, 0xc5, 0x2a, 0x49, 0xed, 0xcf, 0x38, 0x17, 0x30, 0xa4, 0xff,
	0x05, 0xb3, 0x40, 0xd6, 0x28, 0x86, 0x75, 0xe8, 0xda, 0xb0, 0xb3, 0xf3, 0xfa, 0xb0, 0xbb, 0x7d,
	0xd6, 0x78, 0xe8, 0x2d, 0x3a, 0xf6, 0x0c, 0x97, 0xc7, 0xfa, 0x0e, 0xa7, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xb6, 0x27, 0x93, 0xfc, 0x98, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/io.agoradb.Gateway/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/io.agoradb.Gateway/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
type GatewayServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
}

// UnimplementedGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedGatewayServer struct {
}

func (*UnimplementedGatewayServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedGatewayServer) Info(ctx context.Context, req *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.agoradb.Gateway/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.agoradb.Gateway/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.agoradb.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Gateway_Ping_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Gateway_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
